MBR.Web/Controllers/ANController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using MBR.Models;
using MBR.Web.Models;

namespace MBR.Web.Controllers
{
    public class ANController : BaseController
    {
        private MBREntities db = new MBREntities();

        public ActionResult Index()
        {
            RouteValueDictionary routeValues = new RouteValueDictionary();
            foreach (string key in Request.QueryString)
            {
                routeValues.Add(key, Request.QueryString[key]);
            }
            if (!routeValues.ContainsKey("type"))
            {
                routeValues.Add("type", "an");
            }
            return RedirectToAction("Index", "MBRInfo", routeValues);
        }

        public ViewResult ANIndex(int? InfoID)
        {
            MBR_Info Info = null;
            if (InfoID.HasValue)
            {
                using (MBREntities db = new MBREntities())
                {
                    Info = db.MBR_Info.Find(InfoID.Value);
                }
            }
            if (Info == null) throw new Exception("请选择膜");

            ViewBag.MBRInfo = Info;

            ANInfoModel model = new ANInfoModel();

            using (MBREntities db = new MBREntities())
            {
                model.CLCurve = db.AN_CLCurve.Find(InfoID.Value);
                model.HighCurve = db.AN_HighCurve.Find(InfoID.Value);
                model.LowCurve = db.AN_LowCurve.Find(InfoID.Value);
            }
            model.InfoID = (int)InfoID;
            return View(model);
        }

        /// <summary>
        /// 透水率预测
        /// </summary>
        /// <param name="InfoID"></param>
        /// <returns></returns>
        public JsonResult GetPermeable(int InfoID = 0)
        {



            AN_HighCurve hc = new AN_HighCurve();
            AN_LowCurve lc = new AN_LowCurve();

            using (MBREntities db = new MBREntities())
            {

                hc = db.AN_HighCurve.Find(InfoID);
                lc = db.AN_LowCurve.Find(InfoID);
                
            }
            Dictionary<string, List<ANInfoModel>> dic = new Dictionary<string, List<ANInfoModel>>();

            if (hc != null)
            {
                //高的线的3阶系数
                double hc3 = (double)hc.Coeff_LV3;
                double hc2 = (double)hc.Coeff_LV2;
                double hc1 = (double)hc.Coeff_LV1;
                double hcConst = (double)hc.Const;
                //低线的
                double lc3 = (double)lc.Coeff_LV3;
                double lc2 = (double)lc.Coeff_LV2;
                double lc1 = (double)lc.Coeff_LV1;
                double lcConst = (double)lc.Const;

                List<MBR_WashingInfo> wi = db.MBR_WashingInfo.Where(m => m.InfoID == InfoID).OrderBy(m => m.BeginTime).ToList();

                List<ANInfoModel> highList = new List<ANInfoModel>();

                List<ANInfoModel> lowList = new List<ANInfoModel>();
                for (int i = 0; i <  15; i++)
                {
                    ANInfoModel highAM = new ANInfoModel();
                    //高的线的值
                    double highNumber = hc3 * Math.Pow(i, 3) - hc2 * Math.Pow(i, 2) - hc1 * i + hcConst;//(double)(100 - i)/1.5;//threeSquare + Math.Pow(i, 3) / twoSquare+ Math.Pow(i, 2) + primarySide*i + constant;
                    highAM.XValue = i+1;
                    highAM.YValue = highNumber;
                    highList.Add(highAM);

                    ANInfoModel lowAM = new ANInfoModel();
                    //低的线的值
                    double lowNumber = lc3 * Math.Pow(i, 3) + lc2 * Math.Pow(i, 2) - lc1 * i + lcConst;//(double)(100 - i)/1.5;//threeSquare + Math.Pow(i, 3) / twoSquare+ Math.Pow(i, 2) + primarySide*i + constant;
                    lowAM.XValue = i+1;
                    lowAM.YValue = lowNumber;
                    lowList.Add(lowAM);

                    if (lowNumber >= highNumber)
                    {
                        //清洗之后的值如果小于清洗之前的，吧清洗之前的值赋给之后的，并是最后一次
                        highAM.YValue = lowNumber;
                        break;
                    }
                }
                //清洗之后
                dic.Add("after", highList);
                //清洗之前
                dic.Add("befer", lowList);

                List<ANInfoModel> scaHighList = new List<ANInfoModel>();
                List<ANInfoModel> scaLowList = new List<ANInfoModel>();
                for (int i = 0; i < wi.Count; i++)
                {
                    MBR_WashingInfo rc = wi[i];

                    if (rc.TouShuiL_High == null)
                    {
                        continue;
                    }
                    if (rc.TouShuiL_Low == null)
                    {
                        continue;
                    }


                    ANInfoModel highAM = new ANInfoModel();
                    
                    double highNumber = (double)rc.TouShuiL_High;
                    highAM.XValue = i + 1;
                    highAM.YValue = highNumber;
                    scaHighList.Add(highAM);

                    ANInfoModel lowAM = new ANInfoModel();
                    
                    double lowNumber = (double)rc.TouShuiL_Low;
                    lowAM.XValue = i + 1;
                    lowAM.YValue = lowNumber;
                    scaLowList.Add(lowAM);
                }
                //之后
                dic.Add("afterSca", scaHighList);

                //之前
                dic.Add("beferSca", scaLowList);
                
            }


            return Json(dic, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 累计氯预测
        /// </summary>
        /// <param name="mbrId"></param>
        /// <returns></returns>
        public JsonResult GetChlorinValue(int InfoID = 0, int clcTarget = 0)
        {
            AN_CLCurve cc = new AN_CLCurve();

            Dictionary<string, Object> dic = new Dictionary<string, Object>();
            using (MBREntities db = new MBREntities())
            {
                cc = db.AN_CLCurve.Find(InfoID);
            }
            if (cc != null)
            {
                //高的线的3阶系数
                double cc3 = (double)cc.Coeff_LV3;
                double cc2 = (double)cc.Coeff_LV2;
                double cc1 = (double)cc.Coeff_LV1;
                double ccConst = (double)cc.Const;
                List<MBR_WashingInfo> wi = db.MBR_WashingInfo.Where(m => m.InfoID == InfoID).OrderBy(m => m.BeginTime).ToList();

                List<ANInfoModel> clcList = new List<ANInfoModel>();
                for (int i = 0; i <  15; i++)
                {
                    ANInfoModel clcAM = new ANInfoModel();
                    //高的线的值
                    //-0.0005* Math.Pow(i, 3) + 0.2979* Math.Pow(i, 2) + 3.1688*i + 1.7863;
                    double clcNumber = cc3 * Math.Pow(i, 3) + cc2 * Math.Pow(i, 2) + cc1 * i + ccConst;//(double)(100 - i)/1.5;//threeSquare + Math.Pow(i, 3) / twoSquare+ Math.Pow(i, 2) + primarySide*i + constant;
                    clcAM.XValue = i+1;
                    clcAM.YValue = clcNumber;
                    clcList.Add(clcAM);

                    //if (clcNumber >= maxChlorine)
                    //{
                        //clcAM.YValue = maxChlorine;
                        //break;
                    //}
                }
                dic.Add("lineList", clcList);

                List<ANInfoModel> sacList = new List<ANInfoModel>();
                for (int i = 0; i < wi.Count; i++)
                {
                    MBR_WashingInfo rc = wi[i];
                    if (rc.LvJieCZDC == null)
                    {
                        continue;
                    }
                    


                    ANInfoModel clcAM = new ANInfoModel();
                    double clcNumber = (double)rc.LvJieCZDC;
                    clcAM.XValue = i + 1;
                    clcAM.YValue = clcNumber;
                    sacList.Add(clcAM);
                }

                dic.Add("scaList", sacList);

                dic.Add("plotLineValue", clcTarget);
            }
            return Json(dic, JsonRequestBehavior.AllowGet);
        }

    }
}

MBR.Web/Controllers/MBRInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MBR.Models;
using System.Linq.Expressions;
using MBR.Web.Services;
using MBR.Web.Models;

namespace MBR.Web.Controllers
{
    public class MBRInfoController : BaseController
    {
        public ViewResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View(new MBR_Info
            {
                ChangeDate = DateTime.Now
            });
        }

        public ActionResult Edit(int id)
        {
            MBR_Info entity = null;
            using (MBREntities db = new MBREntities())
            {
                entity = db.MBR_Info.Include("MBR_Pool").Where(m => m.InfoID == id).FirstOrDefault();
            }
            return View(entity);
        }

        public JsonResult GetList(GridPager pager)
        {
            Expression<Func<MBR_Info, bool>> predicate = null;
            if (CurrentMBRPoolID > 0)
            {
                predicate = m => m.PoolID == CurrentMBRPoolID;
            }
            using (MBREntities db = new MBREntities())
            {
                MBRInfoService us = new MBRInfoService(db);

                var query = us.GetList(ref pager, predicate);
                var json = new
                {
                    draw = pager.draw,
                    recordsTotal = pager.recordsFiltered,
                    recordsFiltered = pager.recordsTotal,
                    data = query.Select(m => new { m.InfoID, m.PoolID, m.ChangeDate, m.Company, m.Model, m.Title })
                };
                return Json(json, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult Create(MBR_Info entity)
        {
            using (MBREntities db = new MBREntities())
            {
                MBRInfoService us = new MBRInfoService(db);
                if (us.Create(ref errors, entity))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "InfoID:" + entity.InfoID + ",Title:" + entity.Title, Resource.InsertSucceed, Resource.Create, "MBR膜管理");
                    return Json(JsonHandler.CreateMessage(1, Resource.InsertSucceed), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "InfoID:" + entity.InfoID + ",Title:" + entity.Title, Resource.InsertFail, Resource.Create, "MBR膜管理");
                    return Json(JsonHandler.CreateMessage(0, Resource.InsertFail + ErrorCol), JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public JsonResult Edit(MBR_Info entity)
        {
            if (entity != null && ModelState.IsValid)
            {
                using (MBREntities db = new MBREntities())
                {
                    MBRInfoService us = new MBRInfoService(db);

                    if (us.Edit(ref errors, entity))
                    {
                        LogHandler.WriteServiceLog(LogonUser.RealName, "InfoID:" + entity.InfoID + ",Title:" + entity.Title, Resource.EditSucceed, Resource.Edit, "MBR膜管理");
                        return Json(JsonHandler.CreateMessage(1, Resource.EditSucceed));
                    }
                    else
                    {
                        string ErrorCol = errors.Error;
                        LogHandler.WriteServiceLog(LogonUser.RealName, "InfoID:" + entity.InfoID + ",Title:" + entity.Title, Resource.EditFail, Resource.Edit, "MBR膜管理");
                        return Json(JsonHandler.CreateMessage(0, Resource.EditFail + ErrorCol));
                    }
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Resource.EditFail));
            }
        }

        public ActionResult Details(int id)
        {
            using (MBREntities db = new MBREntities())
            {
                MBRInfoService us = new MBRInfoService(db);
                MBR_Info entity = us.GetById(id);
                return View(entity);
            }
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            using (MBREntities db = new MBREntities())
            {
                MBRInfoService us = new MBRInfoService(db);
                if (us.Delete(ref errors, id))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "InfoID:" + id, Resource.DeleteSucceed, Resource.Delete, "MBR膜管理");
                    return Json(JsonHandler.CreateMessage(1, Resource.DeleteSucceed));
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "InfoID:" + id, Resource.DeleteFail, Resource.Delete, "MBR膜管理");
                    return Json(JsonHandler.CreateMessage(0, Resource.DeleteFail + ErrorCol));
                }
            }
        }

    }
}

MBR.Web/Views/MBRInfo/Create.cshtml
@model MBR.Models.MBR_Info

@{
    Layout = "~/Views/Shared/_Edit_Layout.cshtml";
    MBR.Models.MBR_Pool MBRPool = ViewBag.CurrentMBRPool;
    if(MBRPool==null)
    {
        return;
    }
}
@using (Ajax.BeginForm("Create", "MBRInfo", null, new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "OnSuccess",
    OnFailure = "OnFailure",
}, new { @class = "form-horizontal", id = "frmEdit" }))
{
    <div class="form-body">
        <div class="form-group">
            <label class="control-label col-xs-3">当前膜池</label>
            <div class="col-xs-9">
                @MBRPool.PoolName
                @Html.Hidden("PoolID", MBRPool.PoolID)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ChangeDate, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.ChangeDate,"{0:yyyy-MM-dd}", new { @class = "form-control",@readonly = true })
                @Html.ValidationMessageFor(m => m.ChangeDate)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Company, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.Company, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Company)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Model, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.Model, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Model)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Title, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title)
            </div>
        </div>
    </div>
}
@section header{
    <link rel="stylesheet" href="~/plugins/datepicker/datepicker3.css">
}
@section scripts{
    <script src="~/plugins/datepicker/bootstrap-datepicker.js"></script>
    <script src="~/plugins/datepicker/locales/bootstrap-datepicker.zh-CN.js"></script>
    <script>
        $(function () {


            $('#ChangeDate').datepicker({
                language: 'zh-CN',
                autoclose: true,
                format: 'yyyy-mm-dd'
            });
        });

        function OnSuccess(data) {
            parent.doSuccess(parent.$('#tbMBRInfo'), data.message);
        }

        function OnFailure(data) {
            parent.doFailure(data.message);
        }
    </script>
}

MBR.Web/Views/MBRInfo/Edit.cshtml
@model MBR.Models.MBR_Info
@{
    Layout = "~/Views/Shared/_Edit_Layout.cshtml";
}
@using (Ajax.BeginForm("Edit", "MBRInfo", null, new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "OnSuccess",
    OnFailure = "OnFailure",
}, new { @class = "form-horizontal", id = "frmEdit" }))
{
    @Html.HiddenFor(m => m.InfoID)
    <div class="form-body">
        <div class="form-group">
            <label class="control-label col-xs-3">膜池</label>
            <div class="col-xs-9">
                @Model.MBR_Pool.PoolName
                @Html.HiddenFor(m=>m.PoolID)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ChangeDate, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.ChangeDate, "{0:yyyy-MM-dd}", new { @class = "form-control", @readonly = true })
                @Html.ValidationMessageFor(m => m.ChangeDate)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Company, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.Company, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Company)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Model, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.Model, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Model)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Title, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title)
            </div>
        </div>
    </div>
}
@section scripts{
    <script>
        function OnSuccess(data) {
            parent.doSuccess(parent.$('#tbMBRInfo'), data.message);
        }

        function OnFailure(data) {
            parent.doFailure(data.message);
        }
    </script>
}

MBR.Web/Views/MBRInfo/Index.cshtml
@using MBR.Models
@using MBR.Web
@{
    Layout = "~/Views/Shared/_Index_Layout.cshtml";
    string Type = Request["type"] ?? "washinginfo";//默认清洗日志及评价
    string sFunctionHtml = "";
    if(Type=="washinginfo")
    {
        sFunctionHtml = "<a href=\"#WashingInfoModal\" onclick=\"OnWashingInfo(' + data + ')\" class=\"btn default btn-xs blue\" data-toggle=\"modal\"><i class=\"fa fa-list\"></i> 进入 </a>";
    }
    else if (Type == "offline")
    {
        sFunctionHtml = "<a href=\"javascript:void(0)\" onclick=\"OnWashingInfo(' + data + ')\" class=\"btn default btn-xs blue\"><i class=\"fa fa-list\"></i> 进入 </a>";
    }
    else if (Type == "an")
    {
        sFunctionHtml = "<a href=\"#WashingInfoModal\" onclick=\"OnWashingInfo(' + data + ')\" class=\"btn default btn-xs blue\" data-toggle=\"modal\"><i class=\"fa fa-list\"></i> 进入 </a>";
    }
}
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                <a id="aCreate" class="btn btn-default btn-sm" href="#EditModal" data-toggle="modal">
                    <i class="fa fa-plus"></i>新增 </a>
                <div class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                </div>
                <table id="tbMBRInfo" class="table table-striped table-bordered table-hover dataTable">
                    <thead>
                        <tr>
                            <th>
                                更换时间
                            </th>
                            <th>
                                厂商
                            </th>
                            <th>
                                规格型号
                            </th>
                            <th>
                                标题简称
                            </th>
                            <th style="width: 200px;">
                                操作
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="EditModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">
                    编辑
                </h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button id="btnEdit" type="button" class="btn btn-primary">
                    保存
                </button>
                <button type="button" class="btn default" data-dismiss="modal">
                    关闭
                </button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="WashingInfoModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg" style="width:98%">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div style="height:100%;overflow:auto;">

                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn default" data-dismiss="modal">
                    关闭
                </button>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script type="text/javascript">
        var GetListUrl = '@Url.Action("GetList")';
        var CreateUrl = '@Url.Action("Create")';
        var EditUrl = '@Url.Action("Edit")';
        var DeleteUrl = '@Url.Action("Delete")';
        var Type = '@Type';
        var WashingInfoUrl = '@Url.Action("WashingInfoIndex", "WashingInfo", new { })';
        var OffLineUrl = '@Url.Action("OffLineIndex", "WashingInfo", new { })';
        var ANUrl = '@Url.Action("ANIndex", "AN", new { })';
    </script>
    <script type="text/javascript">
        $(function () {
            var table = $('#tbMBRInfo').DataTable({
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": GetListUrl,
                    "type": "POST",
                    "data": function (d) {
                        //添加额外的参数传给服务器
                        d.sort = 'ChangeDate';
                        d.order = 'desc';
                    }
                },
                "columns": [
                    { "data": "ChangeDate" },
                    { "data": "Company" },
                    { "data": "Model" },
                    { "data": "Title" },
                    { "data": "InfoID" }
                ],
                "columnDefs": [{
                    "targets": 0,
                    "data": "RunDate",
                    "render": function (data, type, full, meta) {
                        var sData = '';
                        if (data) {
                            sData = data.substr(0, 10); //格式化日期
                        }
                        return sData;
                    }
                }, {
                    "targets": 4,
                    "data": "opt",
                    "render": function (data, type, full, meta) {
                        return '<a href="#EditModal" onclick="OnEdit(' + data + ')" class="btn default btn-xs blue" data-toggle="modal"><i class="fa fa-edit"></i> 编辑 </a>' +
                                    '<a href="javascript:void(0);" onclick="OnDelete(' + data + ')" class="btn default btn-xs blue"><i class="fa fa-trash-o"></i> 删除 </a>' +
                                    '@Html.Raw(sFunctionHtml)';
                    }
                }]


            });

            $('#aCreate').on('click', function (event) {
                var modal = $('#EditModal');
                modal.find('.modal-body').html("<iframe width='100%' height='300' scrolling='no' frameborder='0' src='" + CreateUrl + "'></iframe>");
            })

            $('#btnEdit').on('click', function () {
                window.frames[0].doSubmit('frmEdit');
            });

        });

        function OnEdit(id) {
            var modal = $('#EditModal');
            modal.find('.modal-body').html("<iframe width='100%' height='300' scrolling='no' frameborder='0' src='" + EditUrl + '?id=' + id + "'></iframe>");
        }

        function OnDelete(id) {
            doDelete(DeleteUrl + '/' + id);
        }

        function OnWashingInfo(id) {
            var url = 'about:blank';
            if(Type == 'washinginfo'){
                url = WashingInfoUrl;
                url = AddUrlParam(url,'InfoID',id);
                var modal = $('#WashingInfoModal');
                modal.find('.modal-title').text('膜池清洗记录');
                modal.find('.modal-body div').html("<iframe width='100%' height='350' scrolling='no' frameborder='0' src='" + url + "'></iframe>");
            }
            else if (Type == 'offline') {
                url = OffLineUrl;
                url = AddUrlParam(url, 'InfoID', id);
                window.location = url;
            }
            else if (Type == 'an') {
                url = ANUrl;
                url = AddUrlParam(url, 'InfoID', id);
                var modal = $('#WashingInfoModal');
                modal.find('.modal-title').text('智能预测');
                modal.find('.modal-body div').html("<iframe width='100%' height='550' scrolling='no' frameborder='0' src='" + url + "'></iframe>");
            } 
        }

        function AddUrlParam(url, name, value) {
            if (url.indexOf('?') > -1) {
                url = url + '&';
            }
            else {
                url = url + '?';
            }
            url = url + name + '=' + value;
            return url;
        }
    </script>
}