MBR.Web/Controllers/DATADICTIONARYController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MBR.Web.Models;
using MBR.Models;
using System.Linq.Expressions;
using MBR.Web.Services;

namespace MBR.Web.Controllers
{
    public class DATADICTIONARYController : BaseController
    {


        public JsonResult GetDicValuesByCode(string code)
        {
            DATADICTIONARYService DATADICTIONARYService = new DATADICTIONARYService();

            return Json(DATADICTIONARYService.GetDicValuesByCode(code), JsonRequestBehavior.AllowGet);

        }


    }
}

MBR.Web/Controllers/WarningCondController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MBR.Web.Models;
using MBR.Models;
using System.Linq.Expressions;
using MBR.Web.Services;

namespace MBR.Web.Controllers
{
    public class WarningCondController : BaseController
    {

        public ViewResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Edit(int id)
        {
            WN_WarningCond entity = null;
            using (MBREntities db = new MBREntities())
            {
                entity = db.WN_WarningCond.Include("WN_ParamSett").Where(m => m.WarningCondID == id).FirstOrDefault();
            }
            return View(entity);
        }

        public JsonResult GetList(GridPager pager, int WarningCondID)
        {
            Expression<Func<WN_ParamSett, bool>> predicate = null;

            using (MBREntities db = new MBREntities())
            {

                //var query = db.WN_ParamSett.Where(m => m.WarningCondID == WarningCondID).AsQueryable();
                var query = from m in db.WN_ParamSett
                            join n in db.SYS_ParamInfo on m.ParamID equals n.ParamName
                            where m.WarningCondID == WarningCondID
                            select new
                            {
                                m.ParamSetID,
                                ParamID = n.Title,
                                m.High,
                                m.Low,
                                m.WaitTime
                            };
                var list = query.ToList();
                var json = new
                {
                    draw = pager.draw,
                    recordsTotal = list.Count(),
                    recordsFiltered = list.Count(),
                    data = list.Select(m => new { m.ParamSetID, m.ParamID, m.High, m.Low, m.WaitTime })
                };
                return Json(json, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult Create(WN_WarningCond entity)
        {
            using (MBREntities db = new MBREntities())
            {
                WarningCondService us = new WarningCondService(db);
                if (us.Create(ref errors, entity))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.InsertSucceed, Resource.Create, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(1, Resource.InsertSucceed), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.InsertFail, Resource.Create, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(0, Resource.InsertFail + ErrorCol), JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public JsonResult Edit(WN_WarningCond entity)
        {
            if (entity != null && ModelState.IsValid)
            {
                using (MBREntities db = new MBREntities())
                {
                    WarningCondService us = new WarningCondService(db);

                    if (us.Edit(ref errors, entity))
                    {
                        LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.EditSucceed, Resource.Edit, "预警条件设置");
                        return Json(JsonHandler.CreateMessage(1, Resource.EditSucceed));
                    }
                    else
                    {
                        string ErrorCol = errors.Error;
                        LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.EditFail, Resource.Edit, "预警条件设置");
                        return Json(JsonHandler.CreateMessage(0, Resource.EditFail + ErrorCol));
                    }
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Resource.EditFail));
            }
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            using (MBREntities db = new MBREntities())
            {
                WarningCondService us = new WarningCondService(db);
                if (us.Delete(ref errors, id))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + id, Resource.DeleteSucceed, Resource.Delete, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(1, Resource.DeleteSucceed));
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + id, Resource.DeleteFail, Resource.Delete, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(0, Resource.DeleteFail + ErrorCol));
                }
            }
        }

        [HttpPost]
        public JsonResult CreateParamSett(WN_ParamSett entity)
        {
            using (MBREntities db = new MBREntities())
            {
                ParamSettService us = new ParamSettService(db);
                if (us.Create(ref errors, entity))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.InsertSucceed, Resource.Create, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(1, Resource.InsertSucceed), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.InsertFail, Resource.Create, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(0, Resource.InsertFail + ErrorCol), JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public JsonResult EditParamSett(WN_ParamSett entity)
        {
            if (entity != null && ModelState.IsValid)
            {
                using (MBREntities db = new MBREntities())
                {
                    ParamSettService us = new ParamSettService(db);

                    if (us.Edit(ref errors, entity))
                    {
                        LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.EditSucceed, Resource.Edit, "预警条件设置");
                        return Json(JsonHandler.CreateMessage(1, Resource.EditSucceed));
                    }
                    else
                    {
                        string ErrorCol = errors.Error;
                        LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.EditFail, Resource.Edit, "预警条件设置");
                        return Json(JsonHandler.CreateMessage(0, Resource.EditFail + ErrorCol));
                    }
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Resource.EditFail));
            }
        }

        [HttpPost]
        public JsonResult DeleteParamSett(int id)
        {
            using (MBREntities db = new MBREntities())
            {
                ParamSettService us = new ParamSettService(db);
                if (us.Delete(ref errors, id))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + id, Resource.DeleteSucceed, Resource.Delete, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(1, Resource.DeleteSucceed));
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + id, Resource.DeleteFail, Resource.Delete, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(0, Resource.DeleteFail + ErrorCol));
                }
            }
        }
    }
}

MBR.Web/Controllers/WarningSettController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MBR.Web.Models;
using MBR.Models;
using System.Linq.Expressions;
using MBR.Web.Services;

namespace MBR.Web.Controllers
{
    public class WarningSettController : BaseController
    {
        public ViewResult Index()
        {
            return View();
        }

        public ViewResult WarningSettEdit()
        {
            WarningSettModel model = new WarningSettModel();


            using (MBREntities db = new MBREntities())
            {
                model.Settings = db.Settings.AsQueryable().FirstOrDefault();
            }

            return View(model);
        }


        [HttpPost]
        public JsonResult WarningSettEdit(WarningSettModel entity)
        {

            if (entity == null && entity.Settings == null)
            {
                return Json(JsonHandler.CreateMessage(0, Resource.InsertFail));
            }
            if (!ModelState.IsValid)
            {
                return Json(JsonHandler.CreateMessage(0, Resource.InsertFail));
            }
            using (MBREntities db = new MBREntities())
            {
                SettingsService us = new SettingsService(db);
                if (us.Create(ref errors, entity.Settings))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "SettingsID:" + entity.Settings.SettingsID, Resource.InsertSucceed, Resource.Create, "预警设置管理");
                    return Json(JsonHandler.CreateMessage(1, Resource.InsertSucceed), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "SettingsID:" + entity.Settings.SettingsID, Resource.InsertFail, Resource.Create, "预警设置管理");
                    return Json(JsonHandler.CreateMessage(0, Resource.InsertFail + ErrorCol), JsonRequestBehavior.AllowGet);
                }
            }

        }

        public ActionResult Create()
        {

            List<SelectListItem> WarningLevelList = new List<SelectListItem>();
            DATADICTIONARYService DATADICTIONARYService = new DATADICTIONARYService();
            var dicValues = DATADICTIONARYService.GetDicValuesByCode("WarningLevel");

            if (dicValues != null)
            {
                foreach (var item in dicValues)
                {
                    WarningLevelList.Add(new SelectListItem()
                    {
                        Text = item.Value,
                        Value = item.Key
                    });
                }
            }

            ViewBag.WarningLevel = WarningLevelList;

            return View();
        }

        public ActionResult Edit(int id)
        {
            WN_WarningSett entity = null;
            using (MBREntities db = new MBREntities())
            {
                entity = db.WN_WarningSett.Find(id);
            }

            List<SelectListItem> WarningLevelList = new List<SelectListItem>();
            DATADICTIONARYService DATADICTIONARYService = new DATADICTIONARYService();
            var dicValues = DATADICTIONARYService.GetDicValuesByCode("WarningLevel");

            if (dicValues != null)
            {
                foreach (var item in dicValues)
                {
                    bool selected = item.Key.Equals((entity.WarningLevel ?? 0).ToString());
                    WarningLevelList.Add(new SelectListItem()
                    {
                        Text = item.Value,
                        Value = item.Key,
                        Selected = selected
                    });
                }
            }


            ViewBag.WarningLevel = WarningLevelList;

            return View(entity);
        }

        public JsonResult GetList(GridPager pager)
        {
            Expression<Func<WN_WarningSett, bool>> predicate = null;

            using (MBREntities db = new MBREntities())
            {

                var query = db.WN_WarningSett.AsQueryable();
                var list = query.ToList();
                var json = new
                {
                    draw = pager.draw,
                    recordsTotal = list.Count(),
                    recordsFiltered = list.Count(),
                    data = list.Select(m => new { m.WarningSettID, m.Title, m.WarningLevel, m.WarningInfo })
                };
                return Json(json, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult Create(WN_WarningSett entity)
        {
            using (MBREntities db = new MBREntities())
            {
                WarningSettService us = new WarningSettService(db);
                if (us.Create(ref errors, entity))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningSettID:" + entity.WarningSettID + ",Title:" + entity.Title, Resource.InsertSucceed, Resource.Create, "预警规则设置");
                    return Json(JsonHandler.CreateMessage(1, Resource.InsertSucceed), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningSettID:" + entity.WarningSettID + ",Title:" + entity.Title, Resource.InsertFail, Resource.Create, "预警规则设置");
                    return Json(JsonHandler.CreateMessage(0, Resource.InsertFail + ErrorCol), JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public JsonResult Edit(WN_WarningSett entity)
        {
            if (entity != null && ModelState.IsValid)
            {
                using (MBREntities db = new MBREntities())
                {
                    WarningSettService us = new WarningSettService(db);

                    if (us.Edit(ref errors, entity))
                    {
                        LogHandler.WriteServiceLog(LogonUser.RealName, "WarningSettID:" + entity.WarningSettID + ",Title:" + entity.Title, Resource.EditSucceed, Resource.Edit, "预警规则设置");
                        return Json(JsonHandler.CreateMessage(1, Resource.EditSucceed));
                    }
                    else
                    {
                        string ErrorCol = errors.Error;
                        LogHandler.WriteServiceLog(LogonUser.RealName, "WarningSettID:" + entity.WarningSettID + ",Title:" + entity.Title, Resource.EditFail, Resource.Edit, "预警规则设置");
                        return Json(JsonHandler.CreateMessage(0, Resource.EditFail + ErrorCol));
                    }
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Resource.EditFail));
            }
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            using (MBREntities db = new MBREntities())
            {
                WarningSettService us = new WarningSettService(db);
                if (us.Delete(ref errors, id))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningSettID:" + id, Resource.DeleteSucceed, Resource.Delete, "预警规则设置");
                    return Json(JsonHandler.CreateMessage(1, Resource.DeleteSucceed));
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningSettID:" + id, Resource.DeleteFail, Resource.Delete, "预警规则设置");
                    return Json(JsonHandler.CreateMessage(0, Resource.DeleteFail + ErrorCol));
                }
            }
        }


        public JsonResult GetConditonList(GridPager pager, int WarningSettID = 0)
        {
            Expression<Func<WN_WarningCond, bool>> predicate = null;

            using (MBREntities db = new MBREntities())
            {
                var query = db.WN_WarningCond.Where(m => m.WarningSettID == WarningSettID).AsQueryable();
                var list = query.ToList();
                var json = new
                {
                    draw = pager.draw,
                    recordsTotal = list.Count(),
                    recordsFiltered = list.Count(),
                    data = list.Select(m => new { m.WarningCondID, m.WarningCondDesc })
                };
                return Json(json, JsonRequestBehavior.AllowGet);
            }
        }


    }
}

MBR.Web/Views/WarningSett/Create.cshtml
@model MBR.Models.WN_WarningSett

@{
    Layout = "~/Views/Shared/_Edit_Layout.cshtml";
    
}
@using (Ajax.BeginForm("Create", "WarningSett", null, new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "OnSuccess",
    OnFailure = "OnFailure",
}, new { @class = "form-horizontal", id = "frmEdit" }))
{
    <div class="form-body">
        <div class="form-group">
            @Html.LabelFor(m => m.Title, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.WarningLevel, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @*@Html.TextBoxFor(m => m.WarningLevel, new { @class = "form-control" })*@
                @Html.DropDownList("WarningLevel", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WarningLevel)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.WarningInfo, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.WarningInfo, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WarningInfo)
            </div>
        </div>
    </div>
}
@section header{
}
@section scripts{
    <script>
        $(function () {


        });

        function OnSuccess(data) {
            parent.doSuccess(parent.$('#tbWarningSett'), data.message);
        }

        function OnFailure(data) {
            parent.doFailure(data.message);
        }
    </script>
}

MBR.Web/Views/WarningSett/Edit.cshtml
@model MBR.Models.WN_WarningSett
@{
    Layout = "~/Views/Shared/_Edit_Layout.cshtml";
}
@using (Ajax.BeginForm("Edit", "WarningSett", null, new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "OnSuccess",
    OnFailure = "OnFailure",
}, new { @class = "form-horizontal", id = "frmEdit" }))
{
    @Html.HiddenFor(m => m.WarningSettID)
        <div class="form-body">
        <div class="form-group">
            @Html.LabelFor(m => m.Title, new { @class = "control-label col-xs-3" })
            <div class="col-xs-8">
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.WarningLevel, new { @class = "control-label col-xs-3" })
            <div class="col-xs-8">
                @*@Html.TextBoxFor(m => m.WarningLevel, new { @class = "form-control" })*@
                @Html.DropDownList("WarningLevel", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WarningLevel)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.WarningInfo, new { @class = "control-label col-xs-3" })
            <div class="col-xs-8">
                @Html.TextBoxFor(m => m.WarningInfo, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WarningInfo)
            </div>
        </div>
    </div>
}
    
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">
                        预警条件</h3>
                    <div class="box-tools pull-right">
                        <a id="aCreate" class="btn btn-default btn-sm" href="#CreateModal" data-toggle="modal">
                                    <i class="fa fa-plus"></i>新增 </a>
                    </div>
                </div>
                <div class="box-body">
                    
                    <table id="tbWarningCond" class="table table-striped table-bordered table-hover dataTable">
                        <thead>
                            <tr>
                                <th>
                                    条件说明
                                </th>
                                <th style="width: 200px;">
                                    操作
                                </th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="CreateModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">
                    编辑
                </h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button id="btnCreate" type="button" class="btn btn-primary">
                    保存
                </button>
                <button type="button" class="btn default" data-dismiss="modal">
                    关闭
                </button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="EditModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">
                    编辑
                </h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button id="btnEdit" type="button" class="btn btn-primary">
                    保存
                </button>
                <button type="button" class="btn default" data-dismiss="modal">
                    关闭
                </button>
            </div>
        </div>
    </div>
</div>

@section header{
    <link rel="stylesheet" href="~/plugins/datatables/dataTables.bootstrap.css">
}
@section scripts{
    <script src="~/plugins/bootbox/bootbox.min.js"></script>
    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script type="text/javascript">
        var GetConditonListUrl = '@Url.Action("GetConditonList",new{ WarningSettID = Request["id"]})';
        var CreateUrl = '@Url.Action("Create", "WarningCond",new{ WarningSettID = Request["id"]})';
        var EditUrl = '@Url.Action("Edit", "WarningCond")';
        var DeleteUrl = '@Url.Action("Delete", "WarningCond")';
    </script>
    <script>
        $(function () {
            MES.init();
            var table = $('#tbWarningCond').DataTable({
                "searching": false,
                "processing": true,
                "serverSide": true,
                "paging": false,
                "info": false,
                "ajax": {
                    "url": GetConditonListUrl,
                    "type": "POST",
                    "data": function (d) {
                        //添加额外的参数传给服务器
                        d.sort = 'WarningCondID'; //排序字段
                        d.order = 'desc'; //排序字段
                    }
                },
                "columns": [
                    { "data": "WarningCondDesc" },
                    {
                        "data": "WarningCondID",
                        "render": function (data, type, full, meta) {
                            return '<a href="#EditModal" onclick="OnEdit(' + data + ')" class="btn default btn-xs blue" data-toggle="modal"><i class="fa fa-edit"></i> 编辑 </a>' +
                                    '<a href="javascript:void(0);" onclick="OnDelete(' + data + ')" class="btn default btn-xs blue"><i class="fa fa-trash-o"></i> 删除 </a>';
                        }
                    }
                ]

            });

            $('#aCreate').on('click', function (event) {
                var modal = $('#CreateModal');
                modal.find('.modal-body').html("<iframe name='createFrame' width='100%' height='200' scrolling='no' frameborder='0' src='" + CreateUrl + "'></iframe>");
            })

            $('#btnCreate').on('click', function () {
                window.frames['createFrame'].doSubmit('frmEdit');
            });
            $('#btnEdit').on('click', function () {
                window.frames['editFrame'].doSubmit('frmEdit');
            });

        });

        function OnSuccess(data) {
            parent.doSuccess(parent.$('#tbWarningSett'), data.message);
        }

        function OnFailure(data) {
            parent.doFailure(data.message);
        }


        function OnEdit(id) {
            var modal = $('#EditModal');
            modal.find('.modal-body').html("<iframe name='editFrame' width='100%' height='400' scrolling='no' frameborder='0' src='" + EditUrl + '?id=' + id + "'></iframe>");
        }

        function OnDelete(id) {
            doDelete(DeleteUrl + '/' + id);
        }
    </script>
}