MBR.Web/Controllers/ParamSettController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MBR.Web.Models;
using MBR.Models;
using System.Linq.Expressions;
using MBR.Web.Services;

namespace MBR.Web.Controllers
{
    public class ParamSettController : BaseController
    {

        public ViewResult Index()
        {
            return View();
        }

        public ActionResult Create(int WarningCondID)
        {
            WN_ParamSett entity = new WN_ParamSett();
            entity.WarningCondID = WarningCondID;

            List<SelectListItem> ParamNameList = new List<SelectListItem>();
            SYS_ParamInfoService sysParamInfoService = new SYS_ParamInfoService();
            using (MBREntities db = new MBREntities())
            {
                var list = db.SYS_ParamInfo.OrderBy(m=>m.ParamName).ToList();

                if (list != null)
                {
                    foreach (var item in list)
                    {
                        ParamNameList.Add(new SelectListItem()
                        {
                            Text = item.Title,
                            Value = item.ParamName
                        });
                    }
                }               
            }

            ViewBag.ParamID = ParamNameList;

            return View(entity);
        }

        public ActionResult Edit(int id)
        {
            WN_ParamSett entity = null;
            using (MBREntities db = new MBREntities())
            {
                entity = db.WN_ParamSett.Where(m => m.ParamSetID == id).FirstOrDefault();

                List<SelectListItem> ParamNameList = new List<SelectListItem>();
                SYS_ParamInfoService sysParamInfoService = new SYS_ParamInfoService();
                var list = db.SYS_ParamInfo.OrderBy(m => m.ParamName).ToList();

                if (list != null)
                {
                    foreach (var item in list)
                    {
                        var selected = entity.ParamID.Equals(item.ParamName);
                        
                        ParamNameList.Add(new SelectListItem()
                        {
                            Text = item.Title,
                            Value = item.ParamName,
                            Selected = selected
                        });
                    }
                }

                ViewBag.ParamID = ParamNameList;
            }
            return View(entity);
        }

        [HttpPost]
        public JsonResult Create(WN_ParamSett entity)
        {
            using (MBREntities db = new MBREntities())
            {
                ParamSettService us = new ParamSettService(db);
                if (us.Create(ref errors, entity))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.InsertSucceed, Resource.Create, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(1, Resource.InsertSucceed), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.InsertFail, Resource.Create, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(0, Resource.InsertFail + ErrorCol), JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public JsonResult Edit(WN_ParamSett entity)
        {
            if (entity != null && ModelState.IsValid)
            {
                using (MBREntities db = new MBREntities())
                {
                    ParamSettService us = new ParamSettService(db);

                    if (us.Edit(ref errors, entity))
                    {
                        LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.EditSucceed, Resource.Edit, "预警条件设置");
                        return Json(JsonHandler.CreateMessage(1, Resource.EditSucceed));
                    }
                    else
                    {
                        string ErrorCol = errors.Error;
                        LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + entity.WarningCondID, Resource.EditFail, Resource.Edit, "预警条件设置");
                        return Json(JsonHandler.CreateMessage(0, Resource.EditFail + ErrorCol));
                    }
                }
            }
            else
            {
                return Json(JsonHandler.CreateMessage(0, Resource.EditFail));
            }
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            using (MBREntities db = new MBREntities())
            {
                ParamSettService us = new ParamSettService(db);
                if (us.Delete(ref errors, id))
                {
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + id, Resource.DeleteSucceed, Resource.Delete, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(1, Resource.DeleteSucceed));
                }
                else
                {
                    string ErrorCol = errors.Error;
                    LogHandler.WriteServiceLog(LogonUser.RealName, "WarningCondID:" + id, Resource.DeleteFail, Resource.Delete, "预警条件设置");
                    return Json(JsonHandler.CreateMessage(0, Resource.DeleteFail + ErrorCol));
                }
            }
        }
    }
}

MBR.Web/Views/ParamSett/Create.cshtml
@model MBR.Models.WN_ParamSett

@{
    Layout = "~/Views/Shared/_Edit_Layout.cshtml";
    
}
@using (Ajax.BeginForm("Create", "ParamSett", null, new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "OnSuccess",
    OnFailure = "OnFailure",
}, new { @class = "form-horizontal", id = "frmEdit" }))
{
    @Html.HiddenFor(m => m.WarningCondID, new {  })
    <div class="form-body">
        <div class="form-group">
            @Html.LabelFor(m => m.ParamID, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @*@Html.TextBoxFor(m => m.ParamID, new { @class = "form-control" })*@
                @Html.DropDownList("ParamID", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ParamID)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.WaitTime, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.WaitTime, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WaitTime)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.High, new { @class = "control-label col-xs-3" })
            <div class="col-xs-3">
                @Html.TextBoxFor(m => m.High, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.High)
            </div>
            @Html.LabelFor(m => m.Low, new { @class = "control-label col-xs-3" })
            <div class="col-xs-3">
                @Html.TextBoxFor(m => m.Low, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Low)
            </div>
        </div>
    </div>
}
@section header{
}
@section scripts{
    <script>
        $(function () {


        });

        function OnSuccess(data) {
            parent.doSuccess(parent.$('#tbParamSett'), data.message);
        }

        function OnFailure(data) {
            parent.doFailure(data.message);
        }
    </script>
}

MBR.Web/Views/ParamSett/Edit.cshtml
@model MBR.Models.WN_ParamSett

@{
    Layout = "~/Views/Shared/_Edit_Layout.cshtml";
    
}
@using (Ajax.BeginForm("Edit", "ParamSett", null, new AjaxOptions
{
    HttpMethod = "POST",
    OnSuccess = "OnSuccess",
    OnFailure = "OnFailure",
}, new { @class = "form-horizontal", id = "frmEdit" }))
{
    @Html.HiddenFor(m => m.ParamSetID, new { })
    @Html.HiddenFor(m => m.WarningCondID, new { })
    <div class="form-body">
        <div class="form-group">
            @Html.LabelFor(m => m.ParamID, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @*@Html.TextBoxFor(m => m.ParamID, new { @class = "form-control" })*@
                @Html.DropDownList("ParamID", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ParamID)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.WaitTime, new { @class = "control-label col-xs-3" })
            <div class="col-xs-9">
                @Html.TextBoxFor(m => m.WaitTime, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.WaitTime)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.High, new { @class = "control-label col-xs-3" })
            <div class="col-xs-3">
                @Html.TextBoxFor(m => m.High, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.High)
            </div>
            @Html.LabelFor(m => m.Low, new { @class = "control-label col-xs-3" })
            <div class="col-xs-3">
                @Html.TextBoxFor(m => m.Low, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Low)
            </div>
        </div>
    </div>
}
@section header{
}
@section scripts{
    <script>
        $(function () {


        });

        function OnSuccess(data) {
            parent.doSuccess(parent.$('#tbParamSett'), data.message);
        }

        function OnFailure(data) {
            parent.doFailure(data.message);
        }
    </script>
}